name: Hola mundo
on:
  push:
    branches:
      - main
      - develop
jobs:
  my-first-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir
        env:
          MI_VARIABLE: Hello World!
        run: |
          echo $MI_VARIABLE
      - name: Imprimir 2
        env:
          MI_VARIABLE2: Que berraquera!!
        run: |
          echo $MI_VARIABLE2