name: Hola mundo
on:
  push:
    branches: [ main ]
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir
      env:
        MI_VARIABLE: Hola mundo
      run: |
        echo $MI_VARIABLE.
    - name: Imprimir2
      env:
        MI_VARIABLE: Esto es una berraquera
      run: |
        echo mi nuevo mensaje es: $MI_VARIABLE.